# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  # pushToHockeyApp in local
  lane :pushToHockeyApp do
    # Build
    gym(
      workspace: "YumiMediationMopubAdDemo-iOS.xcworkspace",
      scheme: "YumiMediationMopubAdDemo-iOS",
      configuration: "Release",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      export_method: "enterprise"
    )

    # Push to HockeyApp
    hockey(
      api_token: "b23874100f5346cdb613ca63c57393eb",
      public_identifier: '9b180a9aa6a94fe1a3802d14adbffdbc',
      notify: "1",
      status: "2",
      commit_sha: ENV["TRAVIS_COMMIT"],
      notes: ENV["TRAVIS_COMMIT_MESSAGE"],
    )
  end

  desc "Submit a new Beta Build to App Center"
  lane :pushToAppCenter do
    xcversion(version: "10.2")

    # Build
    gym(
      scheme: "YumiMediationMopubAdDemo-iOS",
      workspace: "YumiMediationMopubAdDemo-iOS.xcworkspace",
      configuration: "Release",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      export_method: "enterprise",
    )

    # push to App Center
    appcenter_upload(
      api_token: "432d532f9c8d234a64d9ffc626d81ba5f9646dae",
      owner_name: "YumiSDK",
      app_name: "MopubAdapter-YumiAd-iOS",
      ipa: "YumiMediationMopubAdDemo-iOS.ipa",
      dsym: "YumiMediationMopubAdDemo-iOS.app.dSYM.zip",
      release_notes: '',
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
  )
  end

end
